# Test Training
policy: MlpPolicy

# Step settings
n_steps: 2048
max_ep_steps: 2048
frame_skip: 1

total_timesteps: 100_000
save_interval: 50_000
eval_freq: 25_000
n_eval_ep: 10

learning_rate: 0.0003


# Reward setup
healthy_reward: 20
y_angle_pen: 0.1
z_angle_pen: 0.1
dist_pen: 100.0
wheel_speed_pen: 0.5

# Curriculum learning
difficulty_grad: 1.0
difficulty_start: 0.0
reset_noise_scale: 2.0